name: Mi primer Workflow de Hola Mundo

run-name: Â¡EjecuciÃ³n de ${{ github.actor }}! ðŸš€

on: [push]

jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Definir variable dinÃ¡micamente
        # 'github.actor' devolverÃ¡ "ccaceres-dev" automÃ¡ticamente
        run: echo "VAR_NOMBRE=${{ github.actor }}" >> $GITHUB_ENV

      - name: Correr script de Python
        run: python hola.py
